"""Added tables business, options, skeleton, user

Revision ID: 609feba3cd28
Revises: 
Create Date: 2022-09-21 23:28:41.266494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '609feba3cd28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='enterprise'
    )
    op.create_table('options',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('parent', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='enterprise'
    )
    op.create_table('skeleton',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('parent', sa.String(), nullable=True),
    sa.Column('business_id', sa.String(), nullable=True, comment='Negocio del Departamento'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['enterprise.business.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='enterprise'
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('fullname', sa.String(length=100), nullable=False),
    sa.Column('dni', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=8), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('skeleton_id', sa.String(), nullable=True, comment='Departamento del Usuario'),
    sa.ForeignKeyConstraint(['skeleton_id'], ['enterprise.skeleton.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username'),
    schema='enterprise'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users', schema='enterprise')
    op.drop_table('skeleton', schema='enterprise')
    op.drop_table('options', schema='enterprise')
    op.drop_table('business', schema='enterprise')
    # ### end Alembic commands ###
